const mongoose = require('mongoose');

const pageContentSchema = new mongoose.Schema({
  pageKey: { type: String, required: true, unique: true },
  heroBadge: { type: String, default: '' },
  heroTitleLine1: { type: String, default: '' },
  heroTitleLine2: { type: String, default: '' },
  heroSubtitle: { type: String, default: '' },
  heroCtaText: { type: String, default: '' },
  heroCtaLink: { type: String, default: '' },
  homeHeroContactText: { type: String, default: 'Liên hệ tư vấn ngay →' },
  homeHeroCoursesText: { type: String, default: 'Khoá học' },
  homeAboutEyebrow: { type: String, default: 'Về VSIA' },
  homeAboutTitle: { type: String, default: 'HỌC VIỆN ĐỔI MỚI SÁNG TẠO STEM VIỆT NAM' },
  homeMissionTitle: { type: String, default: 'Sứ mệnh' },
  homeMissionText: { type: String, default: 'Kiến tạo hệ sinh thái giáo dục STEM cho nhà trường, giáo viên và học sinh Việt Nam, nuôi dưỡng tư duy sáng tạo, năng lực thực hành và bản lĩnh hội nhập.' },
  homeVisionTitle: { type: String, default: 'Tầm nhìn' },
  homeVisionText: { type: String, default: 'Trở thành Học viện tiên phong trong giáo dục STEM và công nghệ số tại Việt Nam, tạo ra giá trị bền vững và vươn tầm tri thức quốc tế.' },
  homeCoreValuesTitle: { type: String, default: 'Giá trị cốt lõi' },
  homeCoreValue1: { type: String, default: 'Đổi mới & Sáng tạo' },
  homeCoreValue2: { type: String, default: 'Chất lượng & Hiệu quả' },
  homeCoreValue3: { type: String, default: 'Tận tâm & Đồng hành' },
  homeCoreValue4: { type: String, default: 'Trách nhiệm & Nhân văn' },
  homeWhyTitle: { type: String, default: 'NĂNG LỰC NỔI BẬT CỦA VSIA' },
  homeWhyItem1Title: { type: String, default: 'Năng lực quản trị dự án cấp quốc gia' },
  homeWhyItem1Text: { type: String, default: 'Là đơn vị điều phối Chương trình tập huấn STEM Innovation Petrovietnam, VSIA khẳng định uy tín và năng lực triển khai các dự án giáo dục quy mô lớn theo tiêu chuẩn khắt khe.' },
  homeWhyItem2Title: { type: String, default: 'Hội đồng cố vấn và khoa học' },
  homeWhyItem2Text: { type: String, default: 'Mọi chương trình đào tạo và giải pháp của VSIA đều được bảo chứng bởi Hội đồng cố vấn gồm các giáo sư, phó giáo sư, tiến sĩ và thạc sĩ giàu kinh nghiệm, đảm bảo chiều sâu học thuật và cập nhật xu hướng quốc tế.' },
  homeWhyItem3Title: { type: String, default: 'Hệ sinh thái giải pháp đồng bộ' },
  homeWhyItem3Text: { type: String, default: 'VSIA không chỉ cung cấp công cụ mà còn giải quyết bài toán giáo dục một cách triệt để thông qua mô hình tích hợp: Thiết kế không gian - Xây dựng chương trình - Đào tạo con người - Vận hành hiệu quả.' },
  homeBusinessEyebrow: { type: String, default: 'Lĩnh vực hoạt động' },
  homeBusiness1Title: { type: String, default: 'ĐÀO TẠO BỒI DƯỠNG CHUYÊN MÔN' },
  homeBusiness1Text: { type: String, default: 'Tổ chức các khóa đào tạo, bồi dưỡng nâng cao năng lực sư phạm và làm chủ công nghệ cho đội ngũ cán bộ quản lý, giáo viên các cấp.' },
  homeBusiness2Title: { type: String, default: 'TỔ CHỨC NGÀY HỘI & CUỘC THI STEM' },
  homeBusiness2Text: { type: String, default: 'Đơn vị tổ chức, điều phối và tư vấn chuyên môn cho các sân chơi công nghệ, ngày hội sáng tạo, giải đấu Robotics từ cấp trường đến cấp quốc gia.' },
  homeBusiness3Title: { type: String, default: 'THIẾT KẾ VÀ CHUYỂN GIAO CHƯƠNG TRÌNH GIÁO DỤC' },
  homeBusiness3Text: { type: String, default: 'Cung cấp giải pháp toàn diện từ thiết kế không gian vật lý đến khung chương trình học liệu cho các nhà trường và đối tác doanh nghiệp, địa phương.' },
  homeLearnMoreText: { type: String, default: 'Tìm hiểu thêm →' },
  homeTrainingEyebrow: { type: String, default: 'Chương trình đào tạo' },
  homeTrainingTitle: { type: String, default: 'CÁC KHOÁ ĐÀO TẠO STEM DÀNH CHO GIÁO VIÊN' },
  homeTrainingLead: { type: String, default: 'Do VSIA tổ chức, dành cho giáo viên các cấp trên toàn quốc.' },
  homeTrainingEmpty: { type: String, default: 'Chưa có khoá học nào. Chạy node seed.js để thêm dữ liệu mẫu.' },
  // 5 chương trình trong khối "Lộ trình đào tạo" (views/partials/training-roadmap.ejs).
  trainingProgram1Title: { type: String, default: 'Tập huấn, đào tạo kỹ thuật' },
  trainingProgram1Text: { type: String, default: 'Hướng dẫn giáo viên sử dụng, vận hành và khai thác thiết bị STEM, Robotics, AI trong phòng thực hành.' },
  trainingProgram2Title: { type: String, default: 'Tổng quan giáo dục STEM trong CTGDPT' },
  trainingProgram2Text: { type: String, default: 'Trang bị kiến thức nền tảng về giáo dục STEM và định hướng triển khai trong Chương trình giáo dục phổ thông.' },
  trainingProgram3Title: { type: String, default: 'Thực hành xây dựng các chủ đề dạy học STEM' },
  trainingProgram3Text: { type: String, default: 'Thực hành thiết kế và tổ chức các chủ đề dạy học STEM gắn với thực tiễn lớp học.' },
  trainingProgram4Title: { type: String, default: 'Nghiên cứu KHKT trong Giáo dục phổ thông' },
  trainingProgram4Text: { type: String, default: 'Trang bị phương pháp tổ chức và hướng dẫn học sinh thực hiện nghiên cứu khoa học kỹ thuật.' },
  trainingProgram5Title: { type: String, default: 'Thực hành các chủ đề nghiên cứu KHKT' },
  trainingProgram5Text: { type: String, default: 'Thực hành xây dựng đề tài, dự án nghiên cứu khoa học kỹ thuật cùng học sinh.' },
  homeViewAllText: { type: String, default: 'Xem tất cả' },
  homeGalleryEyebrow: { type: String, default: 'Hình ảnh' },
  homeGalleryTitle: { type: String, default: 'DỰ ÁN VÀ HOẠT ĐỘNG STEM NỔI BẬT' },
  homeGalleryLead: { type: String, default: 'VSIA là đơn vị triển khai CHƯƠNG TRÌNH TẬP HUẤN STEM INNOVATION PETROVIETNAM' },
  homeGalleryEmpty: { type: String, default: 'Chưa có ảnh/video, thêm ở trang quản trị (/admin/thu-vien).' },
  homeGalleryViewAllText: { type: String, default: 'Xem tất cả →' },
  homeNewsEyebrow: { type: String, default: 'TIN TỨC VÀ SỰ KIỆN GIÁO DỤC STEM' },
  homeNewsTitle: { type: String, default: 'TIN TỨC STEM TRONG NƯỚC VÀ QUỐC TẾ' },
  homeNewsEmpty: { type: String, default: 'Chưa có bài viết nào.' },
  homeTeamEyebrow: { type: String, default: 'Đội ngũ' },
  homeTeamTitle: { type: String, default: 'HỘI ĐỒNG CỐ VẤN VÀ KHOA HỌC' },
  homeTeamLead: { type: String, default: 'Đội ngũ cố vấn chuyên môn đồng hành cùng VSIA trong các chương trình giáo dục STEM.' },
  homeTeamEmpty: { type: String, default: 'Chưa có thông tin Hội đồng chuyên gia. Thêm ở trang quản trị (/admin/doi-ngu).' },
  homePartnersEyebrow: { type: String, default: 'Đối tác đồng hành' },
  homePartnersTitle: { type: String, default: 'CÁC ĐƠN VỊ, TỔ CHỨC ĐỒNG HÀNH CÙNG VSIA' },
  homePartnersEmpty: { type: String, default: 'Chưa có đối tác nào. Thêm ở trang quản trị (/admin/doi-tac).' },
  homeCtaTitle: { type: String, default: 'ĐỒNG HÀNH PHÁT TRIỂN STEM BỀN VỮNG TẠI CÁC ĐỊA PHƯƠNG VÀ NHÀ TRƯỜNG' },
  homeCtaText: { type: String, default: 'VSIA tư vấn, thiết kế và đồng hành triển khai giải pháp giáo dục STEM toàn diện — từ đề án đến đánh giá.' },
  homeContactText: { type: String, default: 'Liên hệ tư vấn →' },
  homeActivityText: { type: String, default: 'Xem lịch hoạt động' },
}, { timestamps: true });

module.exports = mongoose.model('PageContent', pageContentSchema);
