const mongoose = require('mongoose');

const pageContentSchema = new mongoose.Schema({
  pageKey: { type: String, required: true, unique: true },
  heroBadge: { type: String, default: '' },
  heroTitleLine1: { type: String, default: '' },
  heroTitleLine2: { type: String, default: '' },
  heroSubtitle: { type: String, default: '' },
  heroCtaText: { type: String, default: '' },
  heroCtaLink: { type: String, default: '' },
  homeHeroContactText: { type: String, default: 'Liên hệ tư vấn ngay →' },
  homeHeroCoursesText: { type: String, default: 'Khoá học' },
  homeAboutEyebrow: { type: String, default: 'Về VSIA' },
  homeAboutTitle: { type: String, default: 'Vì sao chọn VSIA?' },
  homeMissionTitle: { type: String, default: 'Sứ mệnh' },
  homeMissionText: { type: String, default: 'Kiến tạo hệ sinh thái giáo dục STEM cho nhà trường, giáo viên và học sinh Việt Nam, nuôi dưỡng tư duy sáng tạo, năng lực thực hành và bản lĩnh hội nhập.' },
  homeVisionTitle: { type: String, default: 'Tầm nhìn' },
  homeVisionText: { type: String, default: 'Trở thành Học viện tiên phong trong giáo dục STEM và công nghệ số tại Việt Nam, tạo ra giá trị bền vững và vươn tầm tri thức quốc tế.' },
  homeCoreValuesTitle: { type: String, default: 'Giá trị cốt lõi' },
  homeCoreValue1: { type: String, default: 'Đổi mới & Sáng tạo' },
  homeCoreValue2: { type: String, default: 'Chất lượng & Hiệu quả' },
  homeCoreValue3: { type: String, default: 'Tận tâm & Đồng hành' },
  homeCoreValue4: { type: String, default: 'Trách nhiệm & Nhân văn' },
  homeWhyTitle: { type: String, default: 'Năng lực nổi bật của VSIA' },
  homeWhyItem1Title: { type: String, default: 'Năng lực quản trị dự án cấp quốc gia' },
  homeWhyItem1Text: { type: String, default: 'Là đơn vị điều phối Chương trình tập huấn STEM Innovation Petrovietnam, VSIA khẳng định uy tín và năng lực triển khai các dự án giáo dục quy mô lớn theo tiêu chuẩn khắt khe.' },
  homeWhyItem2Title: { type: String, default: 'Hội đồng cố vấn và khoa học' },
  homeWhyItem2Text: { type: String, default: 'Mọi chương trình đào tạo và giải pháp của VSIA đều được bảo chứng bởi Hội đồng cố vấn gồm các giáo sư, phó giáo sư, tiến sĩ và thạc sĩ giàu kinh nghiệm, đảm bảo chiều sâu học thuật và cập nhật xu hướng quốc tế.' },
  homeWhyItem3Title: { type: String, default: 'Hệ sinh thái giải pháp đồng bộ' },
  homeWhyItem3Text: { type: String, default: 'VSIA không chỉ cung cấp công cụ mà còn giải quyết bài toán giáo dục một cách triệt để thông qua mô hình tích hợp: Thiết kế không gian - Xây dựng chương trình - Đào tạo con người - Vận hành hiệu quả.' },
  homeBusinessEyebrow: { type: String, default: 'Lĩnh vực hoạt động' },
  homeBusiness1Title: { type: String, default: 'Đào tạo & Bồi dưỡng chuyên môn' },
  homeBusiness2Title: { type: String, default: 'Tổ chức & Thẩm định cuộc thi, sự kiện' },
  homeBusiness3Title: { type: String, default: 'Thiết kế & chuyển giao Chương trình giáo dục' },
  homeLearnMoreText: { type: String, default: 'Tìm hiểu thêm →' },
  homeTrainingEyebrow: { type: String, default: 'Chương trình đào tạo' },
  homeTrainingTitle: { type: String, default: 'Các khoá đào tạo STEM dành cho giáo viên' },
  homeTrainingLead: { type: String, default: 'Do VSIA tổ chức, dành cho giáo viên các cấp trên toàn quốc.' },
  homeTrainingEmpty: { type: String, default: 'Chưa có khoá học nào. Chạy node seed.js để thêm dữ liệu mẫu.' },
  homeViewAllText: { type: String, default: 'Xem tất cả' },
  homeGalleryEyebrow: { type: String, default: 'Hình ảnh' },
  homeGalleryTitle: { type: String, default: 'Dự án STEM nổi bật' },
  homeGalleryEmpty: { type: String, default: 'Chưa có ảnh/video, thêm ở trang quản trị (/admin/thu-vien).' },
  homeGalleryViewAllText: { type: String, default: 'Xem tất cả →' },
  homeNewsEyebrow: { type: String, default: 'Tin tức & bài viết' },
  homeNewsTitle: { type: String, default: 'Hoạt động nổi bật' },
  homeNewsEmpty: { type: String, default: 'Chưa có bài viết nào.' },
  homeTeamEyebrow: { type: String, default: 'Đội ngũ' },
  homeTeamTitle: { type: String, default: 'Hội đồng cố vấn và khoa học' },
  homeTeamLead: { type: String, default: 'Đội ngũ cố vấn chuyên môn đồng hành cùng VSIA trong các chương trình giáo dục STEM.' },
  homeTeamEmpty: { type: String, default: 'Chưa có thông tin Hội đồng chuyên gia. Thêm ở trang quản trị (/admin/doi-ngu).' },
  homePartnersEyebrow: { type: String, default: 'Đối tác đồng hành' },
  homePartnersTitle: { type: String, default: 'Các đơn vị, tổ chức đồng hành cùng VSIA' },
  homePartnersEmpty: { type: String, default: 'Chưa có đối tác nào. Thêm ở trang quản trị (/admin/doi-tac).' },
  homeCtaTitle: { type: String, default: 'Đồng hành phát triển STEM bền vững tại các địa phương và nhà trường' },
  homeCtaText: { type: String, default: 'VSIA tư vấn, thiết kế và đồng hành triển khai giải pháp giáo dục STEM toàn diện — từ đề án đến đánh giá.' },
  homeContactText: { type: String, default: 'Liên hệ tư vấn →' },
  homeActivityText: { type: String, default: 'Xem lịch hoạt động' },
}, { timestamps: true });

module.exports = mongoose.model('PageContent', pageContentSchema);
